# -*- mode: ruby -*-
# vim: set ft=ruby ts=2 sw=2 et sts=2 :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "{{ project.box.name }}"
  config.vm.box_url = "{{ project.box.url }}"

  config.vm.network :public_network

  config.ssh.forward_agent = true

  # ensure the box can reach the master
  # first delete any reference to the master in the hosts file
  # then add it in with the current master ip
  config.vm.provision :shell,
    inline: 'sed -i -e "/{{ master }}/d" /etc/hosts'
  config.vm.provision :shell,
    inline: 'printf "{{ master_ip }}\t{{ master }}" >> /etc/hosts'

  # provision our box with salt
  config.vm.provision :salt do |salt|
    salt.install_type = "stable"

    salt.minion_config = "salt/minion"
    salt.minion_key = "salt/keys/minion.pem"
    salt.minion_pub = "salt/keys/minion.pub"

    salt.run_highstate = true
  end
end
