# -*- mode: ruby -*-
# vim: set ft=ruby ts=2 sw=2 et sts=2 :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "{{ project.short_name }}-user{{ membership.user.id }}"

  config.vm.box = "{{ project.box.name }}"
  config.vm.box_url = "{{ project.box.url }}"

  config.vm.network :public_network

  config.ssh.forward_agent = true

  config.vm.synced_folder ".", "/home/{{ project.short_name }}/current",
    :mount_options => ["dmode=755", "fmode=755", "uid=6000", "gid=6000"]

  # ensure the box can reach the master
  # first delete any reference to the master in the hosts file
  # then add it in with the current master ip
  config.vm.provision :shell,
    inline: 'sed -i -e "/{{ master }}/d" /etc/hosts'
  config.vm.provision :shell,
    inline: 'printf "{{ master_ip }}\t{{ master }}" >> /etc/hosts'

  # provision our box with salt
  config.vm.provision :salt do |salt|
    salt.verbose = true
    salt.install_type = "stable"

    salt.minion_config = "salt/minion"
    salt.minion_key = "salt/keys/minion.pem"
    salt.minion_pub = "salt/keys/minion.pub"

    salt.run_highstate = true
  end

  config.vm.provision :shell,
    inline: 'echo; echo; echo "Your development environment is now configured"; echo "You can access it at http://{{ project.short_name }}-user{{ membership.user.id }}.local/"; echo'
end
